export const reportsMetadata = [
  {
    name: "Report 121",
    desc: "some desc about the report that will be helpful",
    uri: "1",
    columns: [
      "Field 1",
      "Field 2",
      "Field 3",
      "Field 4",
      "Field 5",
      "Field 6",
      "Field 7",
      "Field 8",
    ],
  },
  {
    name: "Report 2",
    desc: "some desc about the report that will be helpful",
    uri: "2",
    columns: [
      "Field 21",
      "Field 22",
      "Field 23",
      "Field 24",
      "Field 25",
      "Field 26",
      "Field 27",
      "Field 28",
    ],
  },
  {
    name: "Report 3",
    desc: "some desc about the report that will be helpful",
    uri: "3",
    columns: [
      "Field 31",
      "Field 32",
      "Field 33",
      "Field 34",
      "Field 35",
      "Field 36",
      "Field 37",
      "Field 38",
    ],
  },
  {
    name: "Report 4",
    desc: "some desc about the report that will be helpful",
    uri: "4",
    columns: [
      "Field 41",
      "Field 42",
      "Field 43",
      "Field 44",
      "Field 45",
      "Field 46",
      "Field 47",
      "Field 48",
    ],
  },
  {
    name: "Report 5",
    desc: "some desc about the report that will be helpful",
    uri: "5",
    columns: [
      "Field 51",
      "Field 52",
      "Field 53",
      "Field 54",
      "Field 55",
      "Field 56",
      "Field 57",
      "Field 58",
    ],
  },
];
